### ISSUE TITLE
faq editor isn't writing guides with `layout: qna`

### ISSUE THREAD

**Issue by nonowazu** [The-Balance-FFXIV/balance-static#589] opened 2021-11-10 01:46 UTC
It's in the config, but I don't know why it isn't writing. It *could* be because there's the old guides and new. We might need to manually edit these in the feat/getting-glam-orous branch just to make soft launch happen.

**Comment by OHaiDanny** [comment] 2021-11-10 02:53
Hey @nonowazu.

I followed the instructions you given me to replicate and reproduce the issue. I did in the local admin to create some q/a content in netlify and I did notice it was not populating in the WAR's qna page.

I noticed that the WAR's qna page looked different from the SCH's qna page. After investigation it looked like the WAR's qna page was using `single.html` template to generate its data instead of the supposed `qna.html`.

After investigation I checked that there was no issue in the config.yoml file.

I noticed after investigating the template logic that the WAR's faq.md is missing the `layout:qna` parameter and value.
https://cdn.discordapp.com/attachments/877670771256885319/907823360837320744/unknown.png

Once I've added this and refreshed WAR's qna page, it loaded the contents into this template and I was able to see the "testing" content I created using the local admin CMS.

**Comment by OHaiDanny** [comment] 2021-11-10 02:54
![image](https://user-images.githubusercontent.com/6521857/141041082-dfe2a713-b2f4-4f92-bdfe-1159902368f7.png)

**Comment by nonowazu** [comment] 2021-11-10 03:01
Yes, `layout: $item` is how we can select alternative guide layouts (other than just `single.html`) ; we also use another layout for the bis items.

My operating theory is (if you look [here](https://github.com/The-Balance-FFXIV/balance-static/blob/main/static/admin/config.yml#L59)) is that we used to have an old way of writing markdown files, and the "new" way (seen [here](https://github.com/The-Balance-FFXIV/balance-static/blob/main/static/admin/config.yml#L427)) isn't being respected.

My theory for reproduction is:

1. Use "old" way to write some faq entries
2. edit using "new" way
3. breakage

**Comment by OHaiDanny** [comment] 2021-11-10 03:16
Hmmmm I see... Ok let me take another look but this time i'll use the `balance-static` repo to take a look. I was testing all this in the `glam` repo earlier.

**Comment by OHaiDanny** [comment] 2021-11-10 03:27
Interesting... In the line ` - {label: "Layout", name: "layout", widget: "hidden", default: "qna"}` the `default` is not working. I'm looking in Google to see what's going on and it looks like other people have reported this issue as well...

**Comment by OHaiDanny** [comment] 2021-11-10 03:29
it looks like `default` only works on folder structures. Online example below:
![image](https://user-images.githubusercontent.com/6521857/141044632-ffcc3217-a440-4606-86f3-89210c01cb06.png)

**Comment by nonowazu** [comment] 2021-11-10 03:46
Oh boy, that considerably changes things. I'm curious how we made it work with the exampleSite content, to be honest.

**Comment by OHaiDanny** [comment] 2021-11-10 03:51
This is my first time working with Netlify CMS haha, I'm pretty much learning as I go. but in examplePage under the SCH faq.md in the `glam` repo you do see there is `layout: qna`. I believe that existed there before I joined in the project.

**Comment by OHaiDanny** [comment] 2021-11-10 03:55
I'm wondering about what quick solution can we propose to do.... Here is an idea:

1. We turn all these layout `widget:hidden` fields into `widget:string` and remove the default. Then, we manually add the `layout` into all existing content pages that need it.
2. Because we set the layout into a field visible for the content creators that are using the CMS, we communicate to the content creators to add the identifier value `qna, bis, changes` when they create any of these new pages.

What do you think? Thoughts? Let me also ping Roxas to provide additional thoughts too.

**Comment by lailleo** [comment] 2021-11-10 04:01
What precisely would 2 require from our side? Cause I've got to admit that I've not got the slightest idea how we'd do that and I doubt the others do either.

**Comment by OHaiDanny** [comment] 2021-11-10 04:14
The idea for #2 is this shown in this example screenshot. There will be a layout field in the CMS and the content creators will just have to populate this layout field. We will give you the text to add in there depending on if you are creating a qna page, or a best in slot page, or changes page, etc.

![image](https://user-images.githubusercontent.com/6521857/141048411-d724a413-61f0-4be8-99c3-d95113f55a2e.png)

**Comment by OHaiDanny** [comment] 2021-11-10 04:19
Let me look at netlify-cms github in the time being...... it seems like there are conversations about this issue.

**Comment by OHaiDanny** [comment] 2021-11-10 04:28
https://github.com/netlify/netlify-cms/issues/2294 - ugh, doesn't sound too promising

**Comment by lailleo** [comment] 2021-11-10 04:38
> The idea for point number 2 is this shown in this example screenshot. There will be a layout field in the CMS and the content creators will just have to populate this layout field. We will give you the text to add in there depending on if you are creating a qna page, or a best in slot page, or changes page, etc.
> 
> ![image](https://user-images.githubusercontent.com/6521857/141048411-d724a413-61f0-4be8-99c3-d95113f55a2e.png)

Would it be possible to make that a default value and that field to only populate on the FAQ template? If so, I'm sure we can manage.

**Comment by OHaiDanny** [comment] 2021-11-10 04:53
> Would it be possible to make that a default value and that field to only populate on the FAQ template? If so, I'm sure we can manage.

The issue is setting that default value. That feature is somehow not working :(

**Comment by OHaiDanny** [comment] 2021-11-10 04:55
Some more thoughts.... I think the Absolute worst case scenario is that once all the content is created by the content creators, we got in and manually add the `layout` in each of the markdown files that needs it. I know it is manually intensive but lets hear from the other devs on what they think first.

**Comment by ScrubbyXIV** [comment] 2021-11-10 06:18
Hmm it's a bit disappointing that the default value's not working as expected.
Setting it manually wouldn't be the end of the world I think, as we don't have that many pages and it's a pretty simple c&p task.

**Comment by lailleo** [comment] 2021-11-10 06:32
Realistically, we'd just be updating the FAQ pages too and not nuking them entirely, so as long as it's not stripping that each time we update it...

**Comment by OHaiDanny** [comment] 2021-11-10 07:12
@lailleo i've tested the updating and it functions normally once we c&p the `layout` field in each of the markdowns so don't worry about that :)

**Comment by nonowazu** [comment] 2021-11-10 11:30
If we absolutely cannot make it a hidden field, I think we should put the layout field at the bottom, and make it a selection widget with only one option (defaulted to the right layout).

**Comment by OHaiDanny** [comment] 2021-11-10 16:27
Let me take it away and check on how selection widgets work in netlify CMS and ill get back to you all here

**Comment by OHaiDanny** [comment] 2021-11-10 16:50
@nonowazu @lailleo 

unfortunately even for the selection widget, the default value doesn't work 😢 

![image](https://user-images.githubusercontent.com/6521857/141156434-e1c64aaf-2a9b-4d1a-9daf-fdee8f888fc5.png)

However, as you mentioned I can force the dropdown to be that one selection shown below (and force all the other ones to show that dropdown):

![image](https://user-images.githubusercontent.com/6521857/141156479-d7a87699-2dfe-44f8-a027-f0aa5782e1c8.png)

Would this work for now? I think the only effort is for the content creators to re-save those pages and select that layout type.

**Comment by Roxas92** [comment] 2021-11-10 17:00
To keep things a bit more dynamic (also for the future and potential new pages), I'd suggest having a dropdown menu with all available layouts and the one we expect for this page, as a default value.

____

Besides that, I don't think that there is a easy solution for the migration, meaning that we have to open all pages once in the editor in order that the .md files get updated properly. But since this is a one time thing, it should be feasable for now.

**Comment by nonowazu** [comment] 2021-11-10 17:10
I do not think we should allow people to select layouts - we provide only one value for several reasons:

* Since it is a required field, the only option *must* be selected
* Beyond the initial selection it probably won’t be bothered with anyway 
* It prevents accidental editor selection of something else
* The way the pages section of each collection is set up, the “faq” page would only have one possible layout anyway - other selections for that page are wrong

**Comment by OHaiDanny** [comment] 2021-11-10 17:39
I just saw your comment Nono. Let me change some of the code as I initially went with Roxas's multi selection

**Comment by lailleo** [comment] 2021-11-13 03:01
@OHaiDanny any update on this? Was it included in any other PRs?

**Comment by lailleo** [comment] 2021-11-13 03:12
Addressed by #596

**Closed by lailleo** 2021-11-13 03:12 UTC
